version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=weather
      - POSTGRES_USER=weather
      - POSTGRES_PASSWORD=weather
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: weather
      RABBITMQ_DEFAULT_PASS: weather
    ports:
      - 5672:5672
      - 15672:15672